---
language: ruby
cache:
  directories:
  - vendor/bundle
#  - spec/fixtures/modules
sudo: false
branches:
  only:
    - master
    - develop
bundler_args: --without system_tests
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.0"
  allow_failures:
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.0"
notifications:
  email:
    - github@razorsedge.org
